run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - golint
    - ineffassign
    - misspell
    - unconvert
    - unused

issues:
  exclude-use-default: false