version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: avito_shop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: avito_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito_shop_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure

volumes:
  postgres_data: